version: '3.1'
services:
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: abapai824185120
      MYSQL_DATABASE: api_restaurante
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql


  restaurante:
    image: api_restaurante
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/api_restaurante
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: abapai824185120
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data: {}

